# netlify.toml

[build]
  # SPA 单页应用，所有路由都重定向到 index.html
  functions = "netlify/functions" # 指定 Netlify 函数目录（需要复制原始函数目录）

# 配置 Edge Functions
[[edge_functions]]
  function = "inject-env"
  path = "/*"

# 配置重写规则，将 /proxy/* 的请求路由到 proxy 函数
[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

# SPA 路由处理 - 所有页面路由都重定向到 index.html
[[redirects]]
  from = "/s=*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/player.html*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about.html*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/watch.html*"
  to = "/index.html"
  status = 200

# 404 页面也重定向到 index.html (SPA 路由处理)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
